### ISSUE TITLE
if you are using python for backend then use 

### ISSUE THREAD

**Issue by heartlog** [hazaku-rei/Rei-API#2]
* SoundCloud - [scdl](https://github.com/flyingrub/scdl)

* Bandcamp - [Bandcamp](https://github.com/iheanyi/bandcamp-dl)

* youtube-dl - [https://yt-dl.org/](https://yt-dl.org/)

**Comment by hazaku-rei** [comment]
I've never learned Python, and I'm using Node Js
next time I will learn Python :)

**Comment by heartlog** [comment]
> I've never learned Python, and I'm using Node Js next time I will learn Python :)

well i am also thinking of learning node more i only know basic of node 
😆Bruh

**Comment by hazaku-rei** [comment]
well I also just got the basics, let's learn together :)
